services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=financial_organization
      - DB_USER=financial_organization
      - DB_PASSWORD=financial_organization
      - DB_HOST=postgres-fo
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:6-alpine

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A financial_organization.celery worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: postgis/postgis:15-3.3-alpine
    hostname: postgres-fo
    environment:
      - POSTGRES_DB=financial_organization
      - POSTGRES_USER=financial_organization
      - POSTGRES_PASSWORD=financial_organization
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"


  nginx:
    image: nginx:alpine
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

volumes:
  pgdata:
