# Generated by Django 5.1.6 on 2025-03-06 21:42

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('director_board_chairman', models.CharField(blank=True, max_length=512, null=True, verbose_name='Председатель Совета директоров')),
                ('management_board_chairman', models.CharField(blank=True, max_length=512, null=True, verbose_name='Председатель Правления')),
                ('directors_board', models.CharField(blank=True, max_length=512, null=True, verbose_name='Совет директоров')),
                ('management_board_members', models.CharField(blank=True, max_length=512, null=True, verbose_name='Члены Правления')),
                ('chief_accountant', models.CharField(blank=True, max_length=512, null=True, verbose_name='Председатель Совета директоров')),
                ('bin', models.CharField(max_length=12, verbose_name='БИН')),
                ('address', models.CharField(blank=True, help_text='Город, улица, дом, квартира', max_length=512, null=True, verbose_name='Адрес')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Web-сайт')),
                ('license', models.CharField(blank=True, max_length=512, null=True, verbose_name='Лицензия')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialOrganizationNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Контент')),
                ('financial_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='organizations.financialorganization', verbose_name='Финансовая организация')),
            ],
        ),
    ]
