# Generated by Django 5.1.6 on 2025-03-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_financialorganizationnews_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialorganizationnews',
            name='title',
            field=models.CharField(default='', max_length=512, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
